"""remove_deprecated_symbols_field

Revision ID: 55bd28680712
Revises: a94748343e25
Create Date: 2025-08-25 11:07:17.838599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '55bd28680712'
down_revision = 'a94748343e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove deprecated symbols column using Alembic operations (PostgreSQL compatible)
    
    # Check if the symbols column exists before trying to drop it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('universes')]
    
    if 'symbols' in columns:
        # Drop the symbols column if it exists
        op.drop_column('universes', 'symbols')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add symbols column for rollback
    op.add_column('universes', sa.Column('symbols', sa.JSON(), nullable=True))
    # ### end Alembic commands ###