"""remove_deprecated_symbols_field

Revision ID: 55bd28680712
Revises: a94748343e25
Create Date: 2025-08-25 11:07:17.838599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '55bd28680712'
down_revision = 'a94748343e25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove deprecated symbols column
    # SQLite requires table recreation for column removal
    op.execute('''
        CREATE TABLE universes_temp (
            id VARCHAR(36) NOT NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            is_active BOOLEAN NOT NULL,
            name VARCHAR(100) NOT NULL,
            description TEXT,
            screening_criteria JSON,
            last_screening_date DATETIME,
            turnover_rate FLOAT,
            owner_id VARCHAR(36) NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (owner_id) REFERENCES users(id)
        )
    ''')
    
    # Copy data excluding symbols column
    op.execute('''
        INSERT INTO universes_temp 
        SELECT id, created_at, updated_at, is_active, name, description, 
               screening_criteria, last_screening_date, turnover_rate, owner_id
        FROM universes
    ''')
    
    # Drop old table and rename
    op.drop_table('universes')
    op.execute('ALTER TABLE universes_temp RENAME TO universes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add symbols column for rollback
    op.add_column('universes', sa.Column('symbols', sa.JSON(), nullable=True))
    # ### end Alembic commands ###