"""Add Asset and UniverseAsset tables for Phase 2

Revision ID: a94748343e25
Revises: ae6110a8c727
Create Date: 2025-08-23 20:02:04.140585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a94748343e25'
down_revision = 'ae6110a8c727'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BIGINT(), nullable=True),
    sa.Column('pe_ratio', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validation_source', sa.String(length=50), nullable=True),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_is_validated'), 'assets', ['is_validated'], unique=False)
    op.create_index(op.f('ix_assets_sector'), 'assets', ['sector'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('universe_assets',
    sa.Column('universe_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.BIGINT(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_universe_assets_asset', 'universe_assets', ['asset_id'], unique=False)
    op.create_index('idx_universe_assets_composite', 'universe_assets', ['universe_id', 'asset_id'], unique=False)
    op.create_index('idx_universe_assets_universe', 'universe_assets', ['universe_id'], unique=False)
    op.create_index(op.f('ix_universe_assets_asset_id'), 'universe_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_universe_assets_universe_id'), 'universe_assets', ['universe_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN DROP NOT NULL directly
    # This will be handled by the application code during migration
    # The symbols column is already optional in the updated Universe model
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Reverting the nullable change for symbols column is not critical
    # as the application code will handle backward compatibility
    op.drop_index(op.f('ix_universe_assets_universe_id'), table_name='universe_assets')
    op.drop_index(op.f('ix_universe_assets_asset_id'), table_name='universe_assets')
    op.drop_index('idx_universe_assets_universe', table_name='universe_assets')
    op.drop_index('idx_universe_assets_composite', table_name='universe_assets')
    op.drop_index('idx_universe_assets_asset', table_name='universe_assets')
    op.drop_table('universe_assets')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_sector'), table_name='assets')
    op.drop_index(op.f('ix_assets_is_validated'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###