"""add universe snapshots table for temporal universe system

Revision ID: c8c7722f1c31
Revises: 55bd28680712
Create Date: 2025-08-27 23:58:50.653003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c7722f1c31'
down_revision = '55bd28680712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create universe_snapshots table for temporal universe system
    op.create_table('universe_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('universe_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('screening_criteria', sa.JSON(), nullable=True),
    sa.Column('turnover_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('assets_added', sa.JSON(), nullable=True),
    sa.Column('assets_removed', sa.JSON(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'snapshot_date', name='uq_universe_snapshot_date')
    )
    
    # Create indexes for temporal queries
    op.create_index('idx_universe_snapshots_universe_date', 'universe_snapshots', ['universe_id', 'snapshot_date'])
    op.create_index('idx_universe_snapshots_date', 'universe_snapshots', ['snapshot_date'])
    op.create_index('idx_universe_snapshots_universe_id', 'universe_snapshots', ['universe_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index('idx_universe_snapshots_universe_id', table_name='universe_snapshots')
    op.drop_index('idx_universe_snapshots_date', table_name='universe_snapshots')
    op.drop_index('idx_universe_snapshots_universe_date', table_name='universe_snapshots')
    
    # Drop table
    op.drop_table('universe_snapshots')
    # ### end Alembic commands ###